-- ============================================================================
-- Stato corrente dello schema `public` — GENERATO, NON MODIFICARE A MANO.
--
-- Rigenerato il 19/09/2026 leggendo il database (information_schema,
-- pg_constraint, pg_indexes, pg_policies, role_table_grants, pg_proc).
-- Aggiornato dopo P2 (updated_at), P3 (anagrafica produttori) e P1b
-- (soft delete + audit_log).
--
-- Perché esiste, dato che c'è già `migrations/`: la storia recuperata parte da
-- A2b. I passi A0 e A2a furono eseguiti nel SQL Editor e non sono registrati
-- in `supabase_migrations.schema_migrations`, quindi le migrazioni da sole NON
-- ricostruiscono il database da zero. Questo file è l'unica fotografia completa.
--
-- Uso: riferimento per leggere lo schema e per il diff dopo una migrazione.
-- Non è autoritativo: l'autorità è il database, la storia è in migrations/.
-- ============================================================================


-- ─── Tabelle ────────────────────────────────────────────────────────────────

-- P3: l'anagrafica dei produttori. `slow_chiocciola` era un Set hardcoded nel
-- bundle; `sito`/`sito_source` erano la tabella `wine_websites`, ora congelata.
CREATE TABLE public.produttori (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome             text NOT NULL,
  nome_norm        text GENERATED ALWAYS AS (lower(btrim(nome))) STORED UNIQUE,
  sito             text,
  sito_source      text,
  slow_chiocciola  boolean NOT NULL DEFAULT false,
  regione          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.wines (
  id              integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produttore      text      NOT NULL,                        -- legacy, rimossa in P3 fase 3
  produttore_id   integer   NOT NULL REFERENCES public.produttori(id) ON DELETE RESTRICT,
  vino            text      NOT NULL,
  annata          smallint,                        -- A2b: era text NOT NULL DEFAULT 'n.d.'
  tipologia       text      NOT NULL,
  bottiglie       integer   NOT NULL DEFAULT 1,
  prezzo          numeric,                         -- A2b: NULL = prezzo sconosciuto
  vitigno         text,
  macerazione     text,                            -- A2b: NULL invece del placeholder '—'
  fermentazione   text,
  malolattica     text,
  note            text,
  slow_vino_bott  boolean   NOT NULL DEFAULT false,
  created_at      timestamptz        DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),  -- P2: mantenuta da trigger
  denominazione   text,                            -- A2b: NULL invece di 'n.d.'
  valore          numeric,                         -- stima di mercato AI
  note_cantina    text,
  deleted_at      timestamptz,                     -- P1b: NULL = in catalogo.
                                                   -- Valorizzata = eliminato dall'app, riga
                                                   -- conservata. Il client filtra
                                                   -- deleted_at IS NULL; aggiungi_o_incrementa
                                                   -- la riazzera (resurrezione).

  CONSTRAINT wines_bottiglie_check     CHECK (bottiglie >= 0),
  CONSTRAINT wines_prezzo_check        CHECK (prezzo >= 0::numeric),
  CONSTRAINT wines_valore_check        CHECK (valore IS NULL OR valore >= 0::numeric),
  CONSTRAINT wines_tipologia_check     CHECK (tipologia = ANY (ARRAY[
                                         'Rosso fermo','Bianco fermo','Orange',
                                         'Spumante','Spumante rosso','Sidro'])),
  CONSTRAINT wines_denominazione_check CHECK (denominazione IS NULL OR denominazione = ANY (ARRAY[
                                         'DOC','DOCG','IGT','AOC','IGP','QbA','QmP','AVA']))
);

-- Storico immutabile delle bottiglie consumate. Le colonne produttore/vino/
-- annata/tipologia/prezzo sono uno SNAPSHOT del vino al momento del consumo:
-- sopravvivono alla cancellazione della riga in `wines` (FK ON DELETE SET NULL).
-- NB: `annata` qui è text, in `wines` è smallint — divergenza aperta (D4).
CREATE TABLE public.bevuti (
  uid          bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id      integer  REFERENCES public.wines(id) ON DELETE SET NULL,
  nota         text              DEFAULT ''::text,
  created_at   timestamptz       DEFAULT now(),
  rating       numeric(2,1),                       -- A2b: NULL invece del sentinel 0
  produttore   text,
  vino         text,
  annata       text,
  tipologia    text,
  prezzo       numeric,
  consumed_on  date     NOT NULL DEFAULT ((now() AT TIME ZONE 'Europe/Rome'::text))::date,

  CONSTRAINT bevuti_rating_check CHECK (rating IS NULL OR (rating >= 1::numeric AND rating <= 5::numeric))
);

-- Cache: URL dell'immagine bottiglia trovata via Serper. Sono hot-link a siti
-- terzi, destinati a rompersi nel tempo (D7a).
CREATE TABLE public.wine_images (
  wine_id     integer PRIMARY KEY REFERENCES public.wines(id) ON DELETE CASCADE,
  image_url   text    NOT NULL,
  created_at  timestamptz DEFAULT now()
);

-- Cache: sito ufficiale del produttore. La PK è il nome in testo libero, senza
-- FK né normalizzazione: 3 righe su 29 non corrispondono ad alcun vino (D3).
CREATE TABLE public.wine_websites (
  produttore  text PRIMARY KEY,
  url         text NOT NULL,
  source      text DEFAULT 'serper'::text,
  created_at  timestamptz DEFAULT now()
);


-- ─── Indici ─────────────────────────────────────────────────────────────────

-- A2a: dedup lato database. È l'indice su cui fa ON CONFLICT aggiungi_o_incrementa().
CREATE UNIQUE INDEX idx_wines_unique_normalizzato
  ON public.wines (lower(trim(BOTH FROM produttore)), lower(trim(BOTH FROM vino)), annata);

CREATE INDEX idx_bevuti_wine_id ON public.bevuti (wine_id);

CREATE INDEX idx_wines_produttore_id ON public.wines (produttore_id);


-- ─── Trigger ────────────────────────────────────────────────────────────────

-- P2: `set_updated_at()` è SECURITY INVOKER (un trigger non deve elevare
-- privilegi). Attenzione nelle migrazioni future: un backfill di schema deve
-- disabilitare il trigger, altrimenti azzera `updated_at` su tutte le righe.
--   wines_set_updated_at       BEFORE UPDATE ON wines
--   produttori_set_updated_at  BEFORE UPDATE ON produttori


-- ─── Funzioni RPC ───────────────────────────────────────────────────────────
--
-- 9 funzioni SECURITY DEFINER che coprono TUTTE le scritture dell'app (A3).
-- Il corpo corrente è quello definito dalle migrazioni, nell'ordine:
--   20260919090534_a3_identity_and_rpc_functions.sql   (tutte e 9)
--   20260919091547_a3_rpc_returns_jsonb.sql            (4 riscritte per tornare jsonb)
--   20260919093001_bevi_bottiglia_data_modificabile.sql (bevi_bottiglia + p_consumed_on)
--
--   bevi_bottiglia(p_wine_id int, p_nota text, p_rating numeric, p_consumed_on date) -> jsonb
--   riporta_bottiglia(p_uid bigint) -> jsonb
--   elimina_bottiglia(p_wine_id int) -> jsonb
--   aggiungi_o_incrementa(12 parametri) -> wines
--   modifica_vino(14 parametri) -> wines
--   aggiorna_scheda_tecnica(8 parametri) -> wines
--   valuta_vino(p_wine_id int, p_rating numeric) -> jsonb
--   salva_immagine_vino(p_wine_id int, p_image_url text) -> void
--   salva_sito_produttore(p_produttore text, p_url text, p_source text) -> void
--
-- P0  20260919111836 — valuta_vino aggiorna solo la bevuta più recente
-- P3  20260919120944 — risolvi_produttore(p_nome) -> integer (find-or-create,
--     unico punto in cui nasce un produttore); aggiungi_o_incrementa e
--     modifica_vino popolano produttore_id; salva_sito_produttore scrive su
--     `produttori` e non più su `wine_websites`
--
-- P1b 20260920110000 — audit_log: 8 delle 9 RPC registrano la riga COMPLETA
--     PRIMA della modifica, via l'helper registra_audit() non eseguibile
--     dall'esterno. `riporta_bottiglia` ci mette dentro la bevuta cancellata
--     per intero: è l'unico DELETE fisico rimasto, e questo lo rende
--     recuperabile. `salva_immagine_vino` NON logga: è una cache di URL.
--
-- P1b 20260920095905 — elimina_bottiglia non fa più DELETE sull'ultima
--     bottiglia: valorizza wines.deleted_at e azzera bottiglie. Il contratto di
--     ritorno (`eliminato`, `bottiglie_residue`) non cambia.
--     aggiungi_o_incrementa, sullo stesso conflitto, azzera deleted_at: il vino
--     riaggiunto torna con il suo id, la sua immagine e le sue bevute.
--     `idx_wines_unique_normalizzato` resta totale (non parziale) proprio
--     perché è la resurrezione a risolvere il conflitto.
--     La FK wine_images -> wines resta ON DELETE CASCADE: senza più un DELETE
--     non scatta, e toglierla lascerebbe orfani a una cancellazione fisica.
--
-- Nota: bevi_bottiglia esiste in DUE overload (3 e 4 parametri). Quello a 3
-- è residuo di A3 e non è chiamato da nessuno: da rimuovere.
--
-- Nota: riporta_bottiglia contiene l'ALTRO DELETE del sistema (sulla riga di
-- `bevuti`). Non ha soft delete di suo: con Q2 = a la tabella viene assorbita
-- da `bottiglie` in P6, quindi il recupero passa dall'audit log (P1b.3, fatto).


-- ── audit_log (P1b.3) ───────────────────────────────────────────────────────
-- Log append-only. Nessuna FK su wine_id/uid_bevuta di proposito: deve
-- sopravvivere alla sparizione di ciò che descrive.
CREATE TABLE public.audit_log (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at          timestamptz NOT NULL DEFAULT now(),
  azione      text        NOT NULL,   -- bevi|riporta|elimina|aggiungi|modifica|scheda|valuta|sito
  wine_id     integer,                -- senza FK
  uid_bevuta  bigint,                 -- senza FK
  dettaglio   jsonb                   -- la riga COMPLETA prima della modifica
);
CREATE INDEX idx_audit_log_at      ON public.audit_log (at DESC);
CREATE INDEX idx_audit_log_wine_id ON public.audit_log (wine_id) WHERE wine_id IS NOT NULL;

-- RLS attiva con la SOLA policy di SELECT: si legge (serve al backup), non si
-- scrive dall'esterno. Cresce solo via RPC, che sono SECURITY DEFINER.
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_log_sola_lettura ON public.audit_log
  FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.audit_log TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.audit_log FROM anon, authenticated;

-- registra_audit(azione, wine_id, uid, dettaglio) -> void, SECURITY DEFINER.
-- EXECUTE revocata a public/anon/authenticated: un log falsificabile non serve.


-- ── bottiglie (P6 fase 1) ───────────────────────────────────────────────────
-- Una riga per bottiglia fisica. `wines` resta anagrafica dell'etichetta.
-- Popolata dai dati esistenti ma ANCORA NON LETTA da nessuno: in questa fase
-- l'app continua a usare `wines.bottiglie` e `bevuti`. Le RPC arrivano in
-- fase 2, il client in fase 3, il drop del vecchio in fase 4.
--
-- `wine_id` nullable con ON DELETE SET NULL, come `bevuti`: c'e' una bevuta
-- orfana (il Raina Grechetto, vino 76 cancellato prima delle FK di A2a) e lo
-- storico e' immutabile. Lo snapshot produttore/vino/annata/tipologia e'
-- valorizzato solo sulle righe bevute, che per vincolo non cambiano piu'; le
-- giacenze si leggono via join, e da P1b `wines` non si cancella piu' davvero.
CREATE TABLE public.bottiglie (
  id            bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  wine_id       integer     REFERENCES public.wines(id) ON DELETE SET NULL,
  formato       text        NOT NULL DEFAULT 'Standard',
  stato         text        NOT NULL DEFAULT 'in_cantina',
  acquistata_il date,
  prezzo_pagato numeric,
  posizione     text,
  consumed_on   date,
  nota          text,
  rating        numeric(2,1),
  produttore    text,       -- snapshot: solo sulle bevute
  vino          text,
  annata        smallint,
  tipologia     text,
  legacy_uid    bigint,     -- ponte verso bevuti.uid, sparisce in fase 4
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bottiglie_formato_valido CHECK (
    formato IN ('Mezza','Medium','Standard','Litro','Magnum','Jeroboam')),
  CONSTRAINT bottiglie_stato_valido CHECK (stato IN ('in_cantina','bevuta')),
  CONSTRAINT bottiglie_coerenza_consumo CHECK (
    (stato = 'bevuta'     AND consumed_on IS NOT NULL) OR
    (stato = 'in_cantina' AND consumed_on IS NULL AND rating IS NULL)),
  CONSTRAINT bottiglie_rating_valido CHECK (
    rating IS NULL OR (rating >= 1 AND rating <= 5)),
  CONSTRAINT bottiglie_prezzo_valido CHECK (
    prezzo_pagato IS NULL OR prezzo_pagato >= 0)
);
CREATE INDEX idx_bottiglie_wine_id ON public.bottiglie (wine_id);
CREATE INDEX idx_bottiglie_stato   ON public.bottiglie (stato);
CREATE UNIQUE INDEX idx_bottiglie_legacy_uid ON public.bottiglie (legacy_uid)
  WHERE legacy_uid IS NOT NULL;
CREATE TRIGGER bottiglie_set_updated_at BEFORE UPDATE ON public.bottiglie
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
GRANT SELECT ON public.bottiglie TO anon;

-- Migrazione: 50 righe da `bevuti` (stato 'bevuta') + 117 generate da
-- `wines.bottiglie` con generate_series (stato 'in_cantina') = 167 righe.
-- Verificato dopo: somma dei voti 198,7 identica, costo giacenza 1.578,00 €
-- identico.
--
-- P6 fase 2: sei RPC su nove scrivono ora su ENTRAMBI i modelli, a firma
-- invariata — bevi_bottiglia, riporta_bottiglia, elimina_bottiglia,
-- aggiungi_o_incrementa, modifica_vino, valuta_vino. Le altre tre non toccano
-- le bottiglie. L'overload a 3 parametri di bevi_bottiglia (codice morto di
-- A3, annotato in P0) e' stato droppato: da questa fase scriverebbe su bevuti
-- senza toccare bottiglie, cioe' la divergenza che la fase esiste per
-- impedire. In modifica_vino `p_bottiglie` e' un TOTALE, non un delta, quindi
-- la giacenza viene riconciliata; lo snapshot sulle righe bevute non si
-- aggiorna mai, nemmeno se il vino viene rinominato.
--
-- P6 fase 3: aggiungi_o_incrementa e modifica_vino prendono `p_formato`.
-- Sono state DROPPATE e ricreate, non affiancate da un overload: due funzioni
-- che si distinguono per un solo parametro con DEFAULT sono ambigue per
-- PostgREST quando il client ne manda 12. Con il drop+create il client vecchio
-- continua a funzionare e prende il default. In modifica_vino il default e'
-- NULL e significa "non toccare il formato", altrimenti una modifica
-- qualunque riporterebbe a Standard un Magnum gia' registrato.

-- ─── Permessi ───────────────────────────────────────────────────────────────

-- A3 ha revocato le scritture dirette ad anon:
--   anon          -> SELECT (+ REFERENCES, TRIGGER) su tutte e 4 le tabelle
--   authenticated -> tutti i privilegi su tutte e 4 le tabelle
--
-- MA le 9 RPC sono SECURITY DEFINER e hanno GRANT EXECUTE TO anon, quindi
-- chiunque abbia la publishable key (che è nel bundle) può ancora chiamarle.
-- La superficie d'attacco si è spostata, non ridotta: è la criticità D1,
-- in carico a P1/A4 — vedi PIANO_DATI.md.


-- ─── Row Level Security ─────────────────────────────────────────────────────
--
--   wines          RLS ATTIVA   ma con policy permissive (sotto)
--   wine_images    RLS ATTIVA   ma con policy permissive (sotto)
--   produttori     RLS ATTIVA   solo policy SELECT (le scritture passano dalle RPC)
--   bevuti         RLS DISATTIVA  ← advisor Supabase: livello ERROR
--   wine_websites  RLS DISATTIVA  ← advisor Supabase: livello ERROR (legacy, non più letta)
--
-- Le policy esistenti non filtrano nulla: sono tutte USING(true) al ruolo
-- `public`. Il nome "modifica autenticata" dice l'opposto di ciò che fa.
-- Non abilitare RLS sulle due tabelle scoperte senza prima creare le policy:
-- bloccherebbe ogni accesso e l'app smetterebbe di leggere. Ordine corretto
-- in PIANO_DATI.md, passo P1.

-- wines
--   "lettura pubblica"     SELECT  TO public  USING (true)
--   "modifica autenticata" ALL     TO public  USING (true)
-- wine_images
--   "Lettura pubblica"     SELECT  TO public  USING (true)
--   "Scrittura pubblica"   INSERT  TO public  WITH CHECK (true)
--   "Upsert pubblica"      UPDATE  TO public  USING (true)
--   (nessuna policy DELETE: la pulizia avviene solo via CASCADE della FK)
