-- ============================================================================
-- Stato corrente dello schema `public` — GENERATO, NON MODIFICARE A MANO.
--
-- Rigenerato il 19/09/2026 leggendo il database (information_schema,
-- pg_constraint, pg_indexes, pg_policies, role_table_grants, pg_proc).
--
-- Perché esiste, dato che c'è già `migrations/`: la storia recuperata parte da
-- A2b. I passi A0 e A2a furono eseguiti nel SQL Editor e non sono registrati
-- in `supabase_migrations.schema_migrations`, quindi le migrazioni da sole NON
-- ricostruiscono il database da zero. Questo file è l'unica fotografia completa.
--
-- Uso: riferimento per leggere lo schema e per il diff dopo una migrazione.
-- Non è autoritativo: l'autorità è il database, la storia è in migrations/.
-- ============================================================================


-- ─── Tabelle ────────────────────────────────────────────────────────────────

CREATE TABLE public.wines (
  id              integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produttore      text      NOT NULL,
  vino            text      NOT NULL,
  annata          smallint,                        -- A2b: era text NOT NULL DEFAULT 'n.d.'
  tipologia       text      NOT NULL,
  bottiglie       integer   NOT NULL DEFAULT 1,
  prezzo          numeric,                         -- A2b: NULL = prezzo sconosciuto
  vitigno         text,
  macerazione     text,                            -- A2b: NULL invece del placeholder '—'
  fermentazione   text,
  malolattica     text,
  note            text,
  slow_vino_bott  boolean   NOT NULL DEFAULT false,
  created_at      timestamptz        DEFAULT now(),
  denominazione   text,                            -- A2b: NULL invece di 'n.d.'
  valore          numeric,                         -- stima di mercato AI
  note_cantina    text,

  CONSTRAINT wines_bottiglie_check     CHECK (bottiglie >= 0),
  CONSTRAINT wines_prezzo_check        CHECK (prezzo >= 0::numeric),
  CONSTRAINT wines_valore_check        CHECK (valore IS NULL OR valore >= 0::numeric),
  CONSTRAINT wines_tipologia_check     CHECK (tipologia = ANY (ARRAY[
                                         'Rosso fermo','Bianco fermo','Orange',
                                         'Spumante','Spumante rosso','Sidro'])),
  CONSTRAINT wines_denominazione_check CHECK (denominazione IS NULL OR denominazione = ANY (ARRAY[
                                         'DOC','DOCG','IGT','AOC','IGP','QbA','QmP','AVA']))
);

-- Storico immutabile delle bottiglie consumate. Le colonne produttore/vino/
-- annata/tipologia/prezzo sono uno SNAPSHOT del vino al momento del consumo:
-- sopravvivono alla cancellazione della riga in `wines` (FK ON DELETE SET NULL).
-- NB: `annata` qui è text, in `wines` è smallint — divergenza aperta (D4).
CREATE TABLE public.bevuti (
  uid          bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wine_id      integer  REFERENCES public.wines(id) ON DELETE SET NULL,
  nota         text              DEFAULT ''::text,
  created_at   timestamptz       DEFAULT now(),
  rating       numeric(2,1),                       -- A2b: NULL invece del sentinel 0
  produttore   text,
  vino         text,
  annata       text,
  tipologia    text,
  prezzo       numeric,
  consumed_on  date     NOT NULL DEFAULT ((now() AT TIME ZONE 'Europe/Rome'::text))::date,

  CONSTRAINT bevuti_rating_check CHECK (rating IS NULL OR (rating >= 1::numeric AND rating <= 5::numeric))
);

-- Cache: URL dell'immagine bottiglia trovata via Serper. Sono hot-link a siti
-- terzi, destinati a rompersi nel tempo (D7a).
CREATE TABLE public.wine_images (
  wine_id     integer PRIMARY KEY REFERENCES public.wines(id) ON DELETE CASCADE,
  image_url   text    NOT NULL,
  created_at  timestamptz DEFAULT now()
);

-- Cache: sito ufficiale del produttore. La PK è il nome in testo libero, senza
-- FK né normalizzazione: 3 righe su 29 non corrispondono ad alcun vino (D3).
CREATE TABLE public.wine_websites (
  produttore  text PRIMARY KEY,
  url         text NOT NULL,
  source      text DEFAULT 'serper'::text,
  created_at  timestamptz DEFAULT now()
);


-- ─── Indici ─────────────────────────────────────────────────────────────────

-- A2a: dedup lato database. È l'indice su cui fa ON CONFLICT aggiungi_o_incrementa().
CREATE UNIQUE INDEX idx_wines_unique_normalizzato
  ON public.wines (lower(trim(BOTH FROM produttore)), lower(trim(BOTH FROM vino)), annata);

CREATE INDEX idx_bevuti_wine_id ON public.bevuti (wine_id);


-- ─── Funzioni RPC ───────────────────────────────────────────────────────────
--
-- 9 funzioni SECURITY DEFINER che coprono TUTTE le scritture dell'app (A3).
-- Il corpo corrente è quello definito dalle migrazioni, nell'ordine:
--   20260919090534_a3_identity_and_rpc_functions.sql   (tutte e 9)
--   20260919091547_a3_rpc_returns_jsonb.sql            (4 riscritte per tornare jsonb)
--   20260919093001_bevi_bottiglia_data_modificabile.sql (bevi_bottiglia + p_consumed_on)
--
--   bevi_bottiglia(p_wine_id int, p_nota text, p_rating numeric, p_consumed_on date) -> jsonb
--   riporta_bottiglia(p_uid bigint) -> jsonb
--   elimina_bottiglia(p_wine_id int) -> jsonb
--   aggiungi_o_incrementa(12 parametri) -> wines
--   modifica_vino(14 parametri) -> wines
--   aggiorna_scheda_tecnica(8 parametri) -> wines
--   valuta_vino(p_wine_id int, p_rating numeric) -> jsonb
--   salva_immagine_vino(p_wine_id int, p_image_url text) -> void
--   salva_sito_produttore(p_produttore text, p_url text, p_source text) -> void
--
-- Nota: bevi_bottiglia esiste in DUE overload (3 e 4 parametri). Quello a 3
-- è residuo di A3 e non è chiamato da nessuno: da rimuovere.


-- ─── Permessi ───────────────────────────────────────────────────────────────

-- A3 ha revocato le scritture dirette ad anon:
--   anon          -> SELECT (+ REFERENCES, TRIGGER) su tutte e 4 le tabelle
--   authenticated -> tutti i privilegi su tutte e 4 le tabelle
--
-- MA le 9 RPC sono SECURITY DEFINER e hanno GRANT EXECUTE TO anon, quindi
-- chiunque abbia la publishable key (che è nel bundle) può ancora chiamarle.
-- La superficie d'attacco si è spostata, non ridotta: è la criticità D1,
-- in carico a P1/A4 — vedi PIANO_DATI.md.


-- ─── Row Level Security ─────────────────────────────────────────────────────
--
--   wines          RLS ATTIVA   ma con policy permissive (sotto)
--   wine_images    RLS ATTIVA   ma con policy permissive (sotto)
--   bevuti         RLS DISATTIVA  ← advisor Supabase: livello ERROR
--   wine_websites  RLS DISATTIVA  ← advisor Supabase: livello ERROR
--
-- Le policy esistenti non filtrano nulla: sono tutte USING(true) al ruolo
-- `public`. Il nome "modifica autenticata" dice l'opposto di ciò che fa.
-- Non abilitare RLS sulle due tabelle scoperte senza prima creare le policy:
-- bloccherebbe ogni accesso e l'app smetterebbe di leggere. Ordine corretto
-- in PIANO_DATI.md, passo P1.

-- wines
--   "lettura pubblica"     SELECT  TO public  USING (true)
--   "modifica autenticata" ALL     TO public  USING (true)
-- wine_images
--   "Lettura pubblica"     SELECT  TO public  USING (true)
--   "Scrittura pubblica"   INSERT  TO public  WITH CHECK (true)
--   "Upsert pubblica"      UPDATE  TO public  USING (true)
--   (nessuna policy DELETE: la pulizia avviene solo via CASCADE della FK)
