-- ============================================================================
-- P1b.3 — log append-only delle scritture.
--
-- Terzo e ultimo pezzo di P1b. Serve a due cose: capire *cosa* è successo se un
-- giorno i numeri non tornano, e avere il materiale per disfarlo.
--
-- `dettaglio` porta la RIGA COMPLETA PRIMA della modifica (decisione 20/09/2026).
-- È l'unica forma che permette davvero di ricostruire ciò che è andato perso:
-- i soli parametri della chiamata direbbero cosa è stato chiesto, non cosa c'era.
--
-- Copre l'altro DELETE del sistema, quello che il soft delete di P1b.2 non
-- tocca: `riporta_bottiglia` cancella fisicamente la riga di `bevuti`. Dare a
-- `bevuti` un soft delete proprio sarebbe lavoro buttato — con Q2 = a la tabella
-- viene assorbita da `bottiglie` in P6 — quindi la recuperabilità passa da qui:
-- la riga cancellata finisce per intero dentro `dettaglio`.
--
-- Scelte da motivare:
--
-- 1. Nessuna FK su `wine_id` / `uid_bevuta`. È deliberato: il log deve
--    sopravvivere alla sparizione di ciò che descrive. Una FK lo renderebbe
--    cancellabile insieme al vino, cioè inutile proprio nel caso che conta.
--
-- 2. `salva_immagine_vino` NON scrive nel log, a differenza delle altre otto
--    RPC. È una cache di URL indicizzata per wine_id: perderla costa una nuova
--    ricerca, non un dato. Loggarla aggiungerebbe solo rumore. Scrive invece
--    `salva_sito_produttore`, perché dopo P3 tocca l'anagrafica `produttori`,
--    che è dato editoriale (sito, chiocciola, regione).
--
-- 3. RLS attiva con la sola policy di SELECT: il log si legge (serve al backup
--    e all'ispezione) ma non si scrive né si modifica dall'esterno. Cresce solo
--    attraverso le RPC, che sono SECURITY DEFINER e scavalcano la policy.
--    Il contenuto deriva da tabelle già leggibili con la chiave publishable,
--    quindi la SELECT non espone nulla di nuovo.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.audit_log (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at          timestamptz NOT NULL DEFAULT now(),
  azione      text        NOT NULL,
  wine_id     integer,      -- senza FK, di proposito: vedi nota 1
  uid_bevuta  bigint,       -- idem
  dettaglio   jsonb
);

COMMENT ON TABLE public.audit_log IS
  'P1b: log append-only delle scritture. `dettaglio` contiene la riga completa PRIMA della modifica.';

CREATE INDEX IF NOT EXISTS idx_audit_log_at      ON public.audit_log (at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_wine_id ON public.audit_log (wine_id) WHERE wine_id IS NOT NULL;

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS audit_log_sola_lettura ON public.audit_log;
CREATE POLICY audit_log_sola_lettura ON public.audit_log
  FOR SELECT TO anon, authenticated USING (true);

GRANT SELECT ON public.audit_log TO anon, authenticated;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.audit_log FROM anon, authenticated;

-- ── Helper ─────────────────────────────────────────────────────────────────
-- Non eseguibile dall'esterno: se lo fosse, chiunque abbia la chiave potrebbe
-- inquinare il log con righe inventate, e un log falsificabile non serve.
CREATE OR REPLACE FUNCTION public.registra_audit(
  p_azione text, p_wine_id integer, p_uid bigint, p_dettaglio jsonb)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  INSERT INTO audit_log (azione, wine_id, uid_bevuta, dettaglio)
  VALUES (p_azione, p_wine_id, p_uid, p_dettaglio);
$function$;

REVOKE EXECUTE ON FUNCTION public.registra_audit(text, integer, bigint, jsonb)
  FROM public, anon, authenticated;

-- ── Le 8 RPC che toccano dati dell'utente ──────────────────────────────────

CREATE OR REPLACE FUNCTION public.bevi_bottiglia(
  p_wine_id integer, p_nota text DEFAULT ''::text,
  p_rating numeric DEFAULT NULL::numeric, p_consumed_on date DEFAULT CURRENT_DATE)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_wine wines%ROWTYPE; v_uid bigint; v_consumed_on date;
BEGIN
  SELECT * INTO v_wine FROM wines WHERE id = p_wine_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_wine_id; END IF;

  INSERT INTO bevuti (wine_id, nota, rating, produttore, vino, annata, tipologia, prezzo, consumed_on)
  VALUES (p_wine_id, COALESCE(p_nota, ''), p_rating, v_wine.produttore, v_wine.vino, v_wine.annata, v_wine.tipologia, v_wine.prezzo, COALESCE(p_consumed_on, CURRENT_DATE))
  RETURNING bevuti.uid, bevuti.consumed_on INTO v_uid, v_consumed_on;

  UPDATE wines SET bottiglie = GREATEST(bottiglie - 1, 0) WHERE id = p_wine_id;

  PERFORM registra_audit('bevi', p_wine_id, v_uid, jsonb_build_object('wine_prima', to_jsonb(v_wine)));

  RETURN jsonb_build_object('uid', v_uid, 'consumed_on', v_consumed_on, 'bottiglie_residue', GREATEST(v_wine.bottiglie - 1, 0));
END;
$function$;

-- L'unico DELETE fisico rimasto: la riga cancellata va nel log per intero.
CREATE OR REPLACE FUNCTION public.riporta_bottiglia(p_uid bigint)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_wine_id int; v_bottiglie int; v_bevuta jsonb;
BEGIN
  DELETE FROM bevuti WHERE bevuti.uid = p_uid RETURNING to_jsonb(bevuti.*) INTO v_bevuta;
  IF NOT FOUND THEN RAISE EXCEPTION 'Bevuta % non trovata', p_uid; END IF;

  v_wine_id := (v_bevuta->>'wine_id')::int;

  IF v_wine_id IS NOT NULL THEN
    UPDATE wines SET bottiglie = bottiglie + 1 WHERE id = v_wine_id RETURNING bottiglie INTO v_bottiglie;
  END IF;

  PERFORM registra_audit('riporta', v_wine_id, p_uid, jsonb_build_object('bevuta_cancellata', v_bevuta));

  RETURN jsonb_build_object('bottiglie_residue', v_bottiglie);
END;
$function$;

CREATE OR REPLACE FUNCTION public.elimina_bottiglia(p_wine_id integer)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_wine wines%ROWTYPE;
BEGIN
  SELECT * INTO v_wine FROM wines WHERE id = p_wine_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_wine_id; END IF;

  IF v_wine.bottiglie > 1 THEN
    UPDATE wines SET bottiglie = bottiglie - 1 WHERE id = p_wine_id;
    PERFORM registra_audit('elimina', p_wine_id, NULL,
      jsonb_build_object('eliminato', false, 'wine_prima', to_jsonb(v_wine)));
    RETURN jsonb_build_object('eliminato', false, 'bottiglie_residue', v_wine.bottiglie - 1);
  ELSE
    UPDATE wines SET bottiglie = 0, deleted_at = now() WHERE id = p_wine_id;
    PERFORM registra_audit('elimina', p_wine_id, NULL,
      jsonb_build_object('eliminato', true, 'wine_prima', to_jsonb(v_wine)));
    RETURN jsonb_build_object('eliminato', true, 'bottiglie_residue', 0);
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.aggiungi_o_incrementa(
  p_produttore text, p_vino text, p_denominazione text, p_annata smallint,
  p_tipologia text, p_bottiglie integer, p_prezzo numeric, p_vitigno text,
  p_note text, p_macerazione text, p_fermentazione text, p_malolattica text)
RETURNS wines
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_row wines%ROWTYPE; v_produttore_id integer; v_prima jsonb;
BEGIN
  v_produttore_id := risolvi_produttore(p_produttore);

  -- Uguaglianza semplice su annata, non IS NOT DISTINCT FROM: rispecchia
  -- l'indice unico, dove due NULL non collidono. Se qui si usasse IS NOT
  -- DISTINCT FROM, il log direbbe "incrementata" una riga che invece nasce nuova.
  SELECT to_jsonb(w.*) INTO v_prima FROM wines w
  WHERE lower(trim(w.produttore)) = lower(trim(p_produttore))
    AND lower(trim(w.vino)) = lower(trim(p_vino))
    AND w.annata = p_annata;

  INSERT INTO wines (produttore, produttore_id, vino, denominazione, annata, tipologia, bottiglie, prezzo, vitigno, note, macerazione, fermentazione, malolattica, slow_vino_bott)
  VALUES (p_produttore, v_produttore_id, p_vino, p_denominazione, p_annata, p_tipologia, p_bottiglie, p_prezzo, COALESCE(p_vitigno,''), COALESCE(p_note,''), p_macerazione, p_fermentazione, p_malolattica, false)
  ON CONFLICT (lower(trim(produttore)), lower(trim(vino)), annata)
  DO UPDATE SET bottiglie  = wines.bottiglie + EXCLUDED.bottiglie,
                deleted_at = NULL
  RETURNING * INTO v_row;

  PERFORM registra_audit('aggiungi', v_row.id, NULL,
    jsonb_build_object('nuovo', v_prima IS NULL, 'wine_prima', v_prima));

  RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.modifica_vino(
  p_id integer, p_produttore text, p_vino text, p_denominazione text,
  p_annata smallint, p_tipologia text, p_bottiglie integer, p_prezzo numeric,
  p_vitigno text, p_note text, p_note_cantina text, p_macerazione text,
  p_fermentazione text, p_malolattica text)
RETURNS wines
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_row wines%ROWTYPE; v_produttore_id integer; v_prima jsonb;
BEGIN
  v_produttore_id := risolvi_produttore(p_produttore);

  SELECT to_jsonb(w.*) INTO v_prima FROM wines w WHERE w.id = p_id;

  UPDATE wines SET
    produttore = p_produttore, produttore_id = v_produttore_id,
    vino = p_vino, denominazione = p_denominazione, annata = p_annata,
    tipologia = p_tipologia, bottiglie = p_bottiglie, prezzo = p_prezzo, vitigno = COALESCE(p_vitigno,''),
    note = COALESCE(p_note,''), note_cantina = COALESCE(p_note_cantina,''), macerazione = p_macerazione,
    fermentazione = p_fermentazione, malolattica = p_malolattica
  WHERE id = p_id
  RETURNING * INTO v_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_id; END IF;

  PERFORM registra_audit('modifica', p_id, NULL, jsonb_build_object('wine_prima', v_prima));

  RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.aggiorna_scheda_tecnica(
  p_id integer, p_vitigno text DEFAULT NULL::text, p_fermentazione text DEFAULT NULL::text,
  p_macerazione text DEFAULT NULL::text, p_malolattica text DEFAULT NULL::text,
  p_note text DEFAULT NULL::text, p_note_cantina text DEFAULT NULL::text,
  p_valore numeric DEFAULT NULL::numeric)
RETURNS wines
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_row wines%ROWTYPE; v_prima jsonb;
BEGIN
  SELECT to_jsonb(w.*) INTO v_prima FROM wines w WHERE w.id = p_id;

  UPDATE wines SET
    vitigno = COALESCE(p_vitigno, vitigno),
    fermentazione = COALESCE(p_fermentazione, fermentazione),
    macerazione = COALESCE(p_macerazione, macerazione),
    malolattica = COALESCE(p_malolattica, malolattica),
    note = COALESCE(p_note, note),
    note_cantina = COALESCE(p_note_cantina, note_cantina),
    valore = COALESCE(p_valore, valore)
  WHERE id = p_id
  RETURNING * INTO v_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_id; END IF;

  PERFORM registra_audit('scheda', p_id, NULL, jsonb_build_object('wine_prima', v_prima));

  RETURN v_row;
END;
$function$;

CREATE OR REPLACE FUNCTION public.valuta_vino(p_wine_id integer, p_rating numeric)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_uid bigint; v_prima jsonb;
BEGIN
  SELECT uid, to_jsonb(b.*) INTO v_uid, v_prima
  FROM bevuti b
  WHERE wine_id = p_wine_id
  ORDER BY consumed_on DESC, uid DESC
  LIMIT 1;

  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('aggiornate', 0, 'uid', NULL);
  END IF;

  UPDATE bevuti SET rating = p_rating WHERE uid = v_uid;

  PERFORM registra_audit('valuta', p_wine_id, v_uid, jsonb_build_object('bevuta_prima', v_prima));

  RETURN jsonb_build_object('aggiornate', 1, 'uid', v_uid);
END;
$function$;

CREATE OR REPLACE FUNCTION public.salva_sito_produttore(
  p_produttore text, p_url text, p_source text DEFAULT 'serper'::text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE v_id integer; v_prima jsonb;
BEGIN
  v_id := risolvi_produttore(p_produttore);

  SELECT to_jsonb(p.*) INTO v_prima FROM produttori p WHERE p.id = v_id;

  UPDATE produttori SET sito = p_url, sito_source = p_source WHERE id = v_id;

  PERFORM registra_audit('sito', NULL, NULL,
    jsonb_build_object('produttore_id', v_id, 'produttore_prima', v_prima));
END;
$function$;

COMMIT;
