BEGIN;

-- ============================================================================
-- A3 — passo 1: identity su wines.id e bevuti.uid, funzioni RPC atomiche.
-- I permessi diretti ad anon NON vengono ancora toccati in questo passo:
-- l'app in produzione continua a funzionare finché il codice non passa
-- alle RPC. La revoca arriva in un passo successivo separato.
-- ============================================================================

-- ---- Identity su wines.id (continua da MAX(id) attuale) ----
ALTER TABLE wines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('wines','id'), (SELECT COALESCE(MAX(id),0) FROM wines));

-- ---- Identity su bevuti.uid (continua da MAX(uid) attuale, i vecchi uid
-- sono timestamp epoch-ms del client: il nuovo range parte ben oltre) ----
ALTER TABLE bevuti ALTER COLUMN uid ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('bevuti','uid'), (SELECT COALESCE(MAX(uid),0) FROM bevuti));

-- ============================================================================
-- RPC: bevi_bottiglia — insert bevuta + decremento bottiglie, atomico
-- ============================================================================
CREATE OR REPLACE FUNCTION bevi_bottiglia(p_wine_id int, p_nota text DEFAULT '', p_rating numeric DEFAULT NULL)
RETURNS TABLE(uid bigint, consumed_on date, bottiglie_residue int)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_wine wines%ROWTYPE; v_uid bigint; v_consumed_on date;
BEGIN
  SELECT * INTO v_wine FROM wines WHERE id = p_wine_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_wine_id; END IF;

  INSERT INTO bevuti (wine_id, nota, rating, produttore, vino, annata, tipologia, prezzo)
  VALUES (p_wine_id, COALESCE(p_nota, ''), p_rating, v_wine.produttore, v_wine.vino, v_wine.annata, v_wine.tipologia, v_wine.prezzo)
  RETURNING bevuti.uid, bevuti.consumed_on INTO v_uid, v_consumed_on;

  UPDATE wines SET bottiglie = GREATEST(bottiglie - 1, 0) WHERE id = p_wine_id;

  RETURN QUERY SELECT v_uid, v_consumed_on, GREATEST(v_wine.bottiglie - 1, 0);
END;
$$;

-- ============================================================================
-- RPC: riporta_bottiglia — elimina bevuta + riaccredita bottiglia, atomico
-- ============================================================================
CREATE OR REPLACE FUNCTION riporta_bottiglia(p_uid bigint)
RETURNS TABLE(bottiglie_residue int)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_wine_id int; v_bottiglie int;
BEGIN
  DELETE FROM bevuti WHERE bevuti.uid = p_uid RETURNING wine_id INTO v_wine_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Bevuta % non trovata', p_uid; END IF;

  IF v_wine_id IS NOT NULL THEN
    UPDATE wines SET bottiglie = bottiglie + 1 WHERE id = v_wine_id RETURNING bottiglie INTO v_bottiglie;
  END IF;

  RETURN QUERY SELECT v_bottiglie;
END;
$$;

-- ============================================================================
-- RPC: elimina_bottiglia — decrementa di 1 o elimina la riga (CASCADE su wine_images)
-- ============================================================================
CREATE OR REPLACE FUNCTION elimina_bottiglia(p_wine_id int)
RETURNS TABLE(eliminato boolean, bottiglie_residue int)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_bottiglie int;
BEGIN
  SELECT bottiglie INTO v_bottiglie FROM wines WHERE id = p_wine_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_wine_id; END IF;

  IF v_bottiglie > 1 THEN
    UPDATE wines SET bottiglie = bottiglie - 1 WHERE id = p_wine_id;
    RETURN QUERY SELECT false, v_bottiglie - 1;
  ELSE
    DELETE FROM wines WHERE id = p_wine_id;
    RETURN QUERY SELECT true, 0;
  END IF;
END;
$$;

-- ============================================================================
-- RPC: aggiungi_o_incrementa — upsert su indice UNIQUE normalizzato (A2a)
-- ============================================================================
CREATE OR REPLACE FUNCTION aggiungi_o_incrementa(
  p_produttore text, p_vino text, p_denominazione text, p_annata smallint,
  p_tipologia text, p_bottiglie int, p_prezzo numeric, p_vitigno text,
  p_note text, p_macerazione text, p_fermentazione text, p_malolattica text
)
RETURNS wines
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_row wines%ROWTYPE;
BEGIN
  INSERT INTO wines (produttore, vino, denominazione, annata, tipologia, bottiglie, prezzo, vitigno, note, macerazione, fermentazione, malolattica, slow_vino_bott)
  VALUES (p_produttore, p_vino, p_denominazione, p_annata, p_tipologia, p_bottiglie, p_prezzo, COALESCE(p_vitigno,''), COALESCE(p_note,''), p_macerazione, p_fermentazione, p_malolattica, false)
  ON CONFLICT (lower(trim(produttore)), lower(trim(vino)), annata)
  DO UPDATE SET bottiglie = wines.bottiglie + EXCLUDED.bottiglie
  RETURNING * INTO v_row;
  RETURN v_row;
END;
$$;

-- ============================================================================
-- RPC: modifica_vino — update campi vino esistente
-- ============================================================================
CREATE OR REPLACE FUNCTION modifica_vino(
  p_id int, p_produttore text, p_vino text, p_denominazione text, p_annata smallint,
  p_tipologia text, p_bottiglie int, p_prezzo numeric, p_vitigno text, p_note text,
  p_note_cantina text, p_macerazione text, p_fermentazione text, p_malolattica text
)
RETURNS wines
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_row wines%ROWTYPE;
BEGIN
  UPDATE wines SET
    produttore = p_produttore, vino = p_vino, denominazione = p_denominazione, annata = p_annata,
    tipologia = p_tipologia, bottiglie = p_bottiglie, prezzo = p_prezzo, vitigno = COALESCE(p_vitigno,''),
    note = COALESCE(p_note,''), note_cantina = COALESCE(p_note_cantina,''), macerazione = p_macerazione,
    fermentazione = p_fermentazione, malolattica = p_malolattica
  WHERE id = p_id
  RETURNING * INTO v_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_id; END IF;
  RETURN v_row;
END;
$$;

-- ============================================================================
-- RPC: aggiorna_scheda_tecnica — patch parziale (solo campi non-NULL forniti)
-- ============================================================================
CREATE OR REPLACE FUNCTION aggiorna_scheda_tecnica(
  p_id int, p_vitigno text DEFAULT NULL, p_fermentazione text DEFAULT NULL,
  p_macerazione text DEFAULT NULL, p_malolattica text DEFAULT NULL,
  p_note text DEFAULT NULL, p_note_cantina text DEFAULT NULL, p_valore numeric DEFAULT NULL
)
RETURNS wines
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_row wines%ROWTYPE;
BEGIN
  UPDATE wines SET
    vitigno = COALESCE(p_vitigno, vitigno),
    fermentazione = COALESCE(p_fermentazione, fermentazione),
    macerazione = COALESCE(p_macerazione, macerazione),
    malolattica = COALESCE(p_malolattica, malolattica),
    note = COALESCE(p_note, note),
    note_cantina = COALESCE(p_note_cantina, note_cantina),
    valore = COALESCE(p_valore, valore)
  WHERE id = p_id
  RETURNING * INTO v_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'Vino % non trovato', p_id; END IF;
  RETURN v_row;
END;
$$;

-- ============================================================================
-- RPC: valuta_vino — aggiorna il rating di tutte le bevute del vino (comportamento invariato)
-- ============================================================================
CREATE OR REPLACE FUNCTION valuta_vino(p_wine_id int, p_rating numeric)
RETURNS int
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_count int;
BEGIN
  UPDATE bevuti SET rating = p_rating WHERE wine_id = p_wine_id;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- ============================================================================
-- RPC: salva_immagine_vino / salva_sito_produttore — upsert cache immagini/siti
-- ============================================================================
CREATE OR REPLACE FUNCTION salva_immagine_vino(p_wine_id int, p_image_url text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO wine_images (wine_id, image_url) VALUES (p_wine_id, p_image_url)
  ON CONFLICT (wine_id) DO UPDATE SET image_url = EXCLUDED.image_url;
END;
$$;

CREATE OR REPLACE FUNCTION salva_sito_produttore(p_produttore text, p_url text, p_source text DEFAULT 'serper')
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO wine_websites (produttore, url, source) VALUES (p_produttore, p_url, p_source)
  ON CONFLICT (produttore) DO UPDATE SET url = EXCLUDED.url, source = EXCLUDED.source;
END;
$$;

-- ---- Permessi di esecuzione (anon deve poter chiamare le RPC) ----
GRANT EXECUTE ON FUNCTION bevi_bottiglia, riporta_bottiglia, elimina_bottiglia,
  aggiungi_o_incrementa, modifica_vino, aggiorna_scheda_tecnica, valuta_vino,
  salva_immagine_vino, salva_sito_produttore TO anon;

COMMIT;

NOTIFY pgrst, 'reload schema';
