-- ============================================================================
-- P3 fase 1 — anagrafica `produttori` (azione D3). Solo schema: il client non
-- cambia in questo passo, `wines.produttore` resta la colonna letta dall'app.
--
-- Risolve: Slow Wine hardcoded nel bundle, rinomina che oggi tocca 3 tabelle a
-- mano, nessun vincolo sui nomi, niente posto dove mettere la regione.
-- ============================================================================

BEGIN;

CREATE TABLE produttori (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome             text NOT NULL,
  -- Chiave di identità: due scritture che differiscono solo per maiuscole o
  -- spazi non possono più diventare due produttori distinti.
  nome_norm        text GENERATED ALWAYS AS (lower(btrim(nome))) STORED UNIQUE,
  sito             text,
  sito_source      text,
  slow_chiocciola  boolean NOT NULL DEFAULT false,
  regione          text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER produttori_set_updated_at
BEFORE UPDATE ON produttori
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---- Popolamento dai nomi già presenti in wines ----
INSERT INTO produttori (nome)
SELECT DISTINCT ON (lower(btrim(produttore))) produttore
FROM wines
ORDER BY lower(btrim(produttore)), produttore;

-- ---- FK su wines ----
ALTER TABLE wines ADD COLUMN produttore_id integer REFERENCES produttori(id) ON DELETE RESTRICT;

-- Il backfill è una migrazione di schema, non una modifica dell'utente: il
-- trigger di P2 va messo a tacere, altrimenti azzera updated_at su 125 righe
-- e la colonna appena introdotta perde subito il suo valore.
ALTER TABLE wines DISABLE TRIGGER wines_set_updated_at;

UPDATE wines w SET produttore_id = p.id
FROM produttori p
WHERE lower(btrim(w.produttore)) = p.nome_norm;

ALTER TABLE wines ENABLE TRIGGER wines_set_updated_at;

DO $$
DECLARE orfani int;
BEGIN
  SELECT count(*) INTO orfani FROM wines WHERE produttore_id IS NULL;
  IF orfani > 0 THEN
    RAISE EXCEPTION 'ABORT — % vini senza produttore_id dopo il backfill', orfani;
  END IF;
END $$;

ALTER TABLE wines ALTER COLUMN produttore_id SET NOT NULL;
CREATE INDEX idx_wines_produttore_id ON wines (produttore_id);

-- ---- Assorbimento di wine_websites (resta in piedi finché il client non migra) ----
UPDATE produttori p
SET sito = w.url, sito_source = w.source
FROM wine_websites w
WHERE lower(btrim(w.produttore)) = p.nome_norm;

-- ---- Slow Wine: dal bundle al database ----
UPDATE produttori SET slow_chiocciola = true
WHERE nome IN ('Pieropan', 'Ca'' dei Zago', 'Bele Casel', 'Miotto', 'Malibràn', 'Occhipinti');

-- ---- Permessi e RLS, coerenti con `wines` ----
GRANT SELECT ON produttori TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON produttori TO authenticated;

ALTER TABLE produttori ENABLE ROW LEVEL SECURITY;

-- Lettura aperta come per wines. Nessuna policy di scrittura: le scritture
-- passano dalle RPC SECURITY DEFINER, che girano come owner e non sono
-- soggette a RLS. Quando arriverà A4 questa policy va sostituita, non aggiunta.
CREATE POLICY "lettura pubblica" ON produttori FOR SELECT TO public USING (true);

COMMIT;

NOTIFY pgrst, 'reload schema';
